# Import Data

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('UFC_data.csv', index_col=0)

pd.set_option("display.max_columns", 150) #THIS LETS US ACTUALLY SEE THE ROWS!!
pd.set_option("display.max_row", 85)

#Things to note: win = 1 means that the first figher won
data.head(2)

,Name,Height,Weight,Reach,Stance,DOB,SLpm,SAcc,SApm,StrDef,TDAvg,TDAcc,TDDef,SubAvg,AvgTime2Win,Name.1,Height.1,Weight.1,Reach.1,Stance.1,DOB.1,SLpm.1,SAcc.1,SApm.1,StrDef.1,TDAvg.1,TDAcc.1,TDDef.1,SubAvg.1,AvgTime2Win.1,Win
0,Chan Sung Jung,1.7018,145,72,Orthodox,1987,4.58,0.41,3.73,0.60,0.78,0.41,0.77,0.6,5.49,Frankie Edgar,1.6764,145,68,Orthodox,1981,3.60,0.40,2.48,0.68,2.34,0.31,0.65,0.3,15.46,1
1,Volkan Oezdemir,1.8796,205,75,Orthodox,1989,4.88,0.45,4.14,0.55,0.39,0.22,0.80,0.0,8.14,Aleksandar Rakic,1.9304,205,78,Orthodox,1992,5.17,0.52,2.41,0.53,1.20,0.28,0.88,0.3,8.72,1

# IS DATA USABLE?

In [3]:
data.isnull().sum()
#No missing Data

Name             0
Height           0
Weight           0
Reach            0
Stance           0
DOB              0
SLpm             0
SAcc             0
SApm             0
StrDef           0
TDAvg            0
TDAcc            0
TDDef            0
SubAvg           0
AvgTime2Win      0
Name.1           0
Height.1         0
Weight.1         0
Reach.1          0
Stance.1         0
DOB.1            0
SLpm.1           0
SAcc.1           0
SApm.1           0
StrDef.1         0
TDAvg.1          0
TDAcc.1          0
TDDef.1          0
SubAvg.1         0
AvgTime2Win.1    0
Win              0
dtype: int64

In [4]:
data.info()
#types are as expected

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3176 entries, 0 to 3175
Data columns (total 31 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           3176 non-null   object
 1   Height         3176 non-null   float64
 2   Weight         3176 non-null   int64
 3   Reach          3176 non-null   int64
 4   Stance         3176 non-null   object
 5   DOB            3176 non-null   int64
 6   SLpm           3176 non-null   float64
 7   SAcc           3176 non-null   float64
 8   SApm           3176 non-null   float64
 9   StrDef         3176 non-null   float64
 10  TDAvg          3176 non-null   float64
 11  TDAcc          3176 non-null   float64
 12  TDDef          3176 non-null   float64
 13  SubAvg         3176 non-null   float64
 14  AvgTime2Win    3176 non-null   float64
 15  Name.1         3176 non-null   object
 16  Height.1       3176 non-null   float64
 17  Weight.1       3176 non-null   int64
 18  Reach.1        3176 non-null   int64
 19  Stance.1       3176 non-null   object
 20  DOB.1          3176 non-null   int64
 21  SLpm.1         3176 non-null   float64
 22  SAcc.1         3176 non-null   float64
 23  SApm.1         3176 non-null   float64
 24  StrDef.1       3176 non-null   float64
 25  TDAvg.1        3176 non-null   float64
 26  TDAcc.1        3176 non-null   float64
 27  TDDef.1        3176 non-null   float64
 28  SubAvg.1       3176 non-null   float64
 29  AvgTime2Win.1  3176 non-null   float64
 30  Win            3176 non-null   int64
dtypes: float64(20), int64(7), object(4)
memory usage: 794.0+ KB

# Feature Engineering

In [5]:
#Drop Name
data = data.drop("Name", axis=1)
data = data.drop("Name.1", axis=1)


#D.O.B. to Age (easier to use)
data["DOB"] = 2023 - data["DOB"]
data["DOB.1"] = 2023 - data["DOB.1"]
data.rename(columns = {'DOB':'Age', 'DOB.1':'Age.1'}, inplace = True)


cols = data.columns

for name in cols:
    #CHANGE NAMES TO _RED/BLUE
    if name[-2:] == ".1":
        new_name = name[0:-2]+"_RED"
    else:
        new_name = name+"_BLUE"
    data.rename(columns = {name:new_name}, inplace = True)
    name = new_name
    
    #REPLACE CATEGORIES W DUMMY VARIABLES
    if data[name].dtype =='object':
        index = data.columns.get_loc(name) #Cant enumerate since we're adding columns
        dummies = pd.get_dummies(data[name], prefix=name)
        left = data.iloc[:,0:index]
        right = data.iloc[:,index+1:]
        data = pd.concat([left,dummies,right],axis=1) #concat data back

        
data.head()

,Height_BLUE,Weight_BLUE,Reach_BLUE,Stance_BLUE_Open Sta,Stance_BLUE_Orthodox,Stance_BLUE_Southpaw,Stance_BLUE_Switch,Age_BLUE,SLpm_BLUE,SAcc_BLUE,SApm_BLUE,StrDef_BLUE,TDAvg_BLUE,TDAcc_BLUE,TDDef_BLUE,SubAvg_BLUE,AvgTime2Win_BLUE,Height_RED,Weight_RED,Reach_RED,Stance_RED_Open Sta,Stance_RED_Orthodox,Stance_RED_Southpaw,Stance_RED_Switch,Age_RED,SLpm_RED,SAcc_RED,SApm_RED,StrDef_RED,TDAvg_RED,TDAcc_RED,TDDef_RED,SubAvg_RED,AvgTime2Win_RED,Win_BLUE
0,1.7018,145,72,0,1,0,0,36,4.58,0.41,3.73,0.60,0.78,0.41,0.77,0.6,5.49,1.6764,145,68,0,1,0,0,42,3.60,0.40,2.48,0.68,2.34,0.31,0.65,0.3,15.46,1
1,1.8796,205,75,0,1,0,0,34,4.88,0.45,4.14,0.55,0.39,0.22,0.80,0.0,8.14,1.9304,205,78,0,1,0,0,31,5.17,0.52,2.41,0.53,1.20,0.28,0.88,0.3,8.72,1
2,1.7780,185,73,0,1,0,0,32,6.41,0.47,4.46,0.59,3.04,0.50,0.45,0.0,15.00,1.8542,185,74,0,1,0,0,33,3.53,0.43,4.20,0.58,0.33,0.16,0.68,0.0,0.00,1
3,1.7526,135,73,0,1,0,0,36,2.52,0.44,2.43,0.58,2.53,0.59,0.71,1.1,11.29,1.6764,135,72,0,1,0,0,30,2.36,0.33,2.99,0.54,0.25,0.20,0.56,1.0,15.00,1
4,1.8034,155,73,0,1,0,0,38,3.60,0.49,1.80,0.62,0.71,1.00,1.00,0.0,15.00,1.8034,155,70,0,1,0,0,35,2.84,0.41,4.10,0.54,1.27,0.53,0.33,0.0,10.50,1

# Split Data
- Train: Create model parameters
- Valid: Estimate model performance + hyperparameter tuning
- Test: unseen data to do final bet analysis

In [6]:
from sklearn.model_selection import train_test_split

#SPLIT: DATA --> TRAIN + VALID
index_train, index_valid  = train_test_split(np.array(data.index), train_size=0.7, random_state=1)
train = data.loc[index_train,:]
valid =  data.loc[index_valid,:]

#SPLIT: VALID --> TEST + VALID
index_valid, index_test  = train_test_split(np.array(valid.index), train_size=0.7, random_state=1)
test = valid.loc[index_test,:]
valid = valid.loc[index_valid,:]


#Split x and y variables
#y
y_train= train['Win_BLUE'].to_numpy()
y_valid = valid['Win_BLUE'].to_numpy()
y_test = test["Win_BLUE"].to_numpy()

#x
train = train.iloc[:,0:-1]
valid = valid.iloc[:,0:-1]
test = test.iloc[:,0:-1]

#Double check things went okay
total = len(data)
print("Total:",total)
print("TRAIN: Length ",len(train),": Percentage",round(len(train)/total,2))
print("VALID: Length ",len(valid),": Percentage",round(len(valid)/total,2))
print("TEST: Length",len(test),": Percentage",round(len(test)/total,2))
#print(len(train) + len(valid) + len(test))

Total: 3176
TRAIN: Length  2223 : Percentage 0.7
VALID: Length  667 : Percentage 0.21
TEST: Length 286 : Percentage 0.09

# Function: Estimate Performance

In [7]:
from sklearn.metrics import accuracy_score


def estimate_performance(models, name, train=train, valid=valid, y_train=y_train, y_valid=y_valid):
    tests = ["Accuracy"]
    results = pd.DataFrame(0.0, columns=tests, index=name)
    
    for number, model in enumerate(models):
        model.fit(train, y_train)
        predictions = model.predict(valid)
        
        accuracy = round(accuracy_score(y_valid, predictions),2)
        results.iloc[number, 0] = accuracy

    return results

# Untuned Results
- Check several ML models and compare.

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB


Logistic = LogisticRegression()
Boost = GradientBoostingClassifier()
KNN = KNeighborsClassifier()
SVC = SVC()
Tree = DecisionTreeClassifier()
Forest = RandomForestClassifier()
AdaBoost = AdaBoostClassifier()
NB = GaussianNB()

models = [Logistic, Boost, KNN, SVC, Tree, Forest, AdaBoost,NB]
name = ["Logistic Reg", "Gradient Boost", "KNN", "SVC", "Tree", "Forest", "Ada","Naive Bayes"]
results = estimate_performance(models, name)
results

/Users/joshuade/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

                Accuracy
Logistic Reg        0.79
Gradient Boost      0.82
KNN                 0.76
SVC                 0.77
Tree                0.74
Forest              0.83
Ada                 0.81
Naive Bayes         0.58

# Tune Gradient Boost
- Optuna will test many iterations of hyperparameters and give back the best it found. Unlike a random search it will use previous results to inform future searches.

In [9]:
run=False #If you set to false it'll just run a previously found optimum

In [10]:
import optuna
from optuna.samplers import TPESampler
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

if run == True:
    def objective(trial):

        max_depth = trial.suggest_int('max_depth', 1, 20)
        n_estimators = trial.suggest_int('n_estimators', 1, 2000)
        #subsample = trial.suggest_int('subsample', 0,1)

    
        model = GradientBoostingClassifier(n_estimators = n_estimators,
                                           max_depth = max_depth,
                                           subsample = 0.5,
                                           random_state = 1)

        scores = cross_val_score(model, train, y_train, cv = 3,  scoring = 'accuracy')

        return np.mean(scores)

    sampler = TPESampler(seed=42) 
    study = optuna.create_study(direction='maximize', sampler=sampler)
    study.optimize(objective, n_trials = 1000, timeout = 1000)

In [11]:
if run == True:
    Grad_params = study.best_params
    print(Grad_params)
else:
    Grad_params = {'max_depth': 7, 'n_estimators': 1050}


Boosted =  GradientBoostingClassifier(learning_rate = 0.01, subsample = 0.5, **Grad_params, random_state=1)

models = [Boosted]
name = ["Gradient Boost Classifier"]
Boosted_Results = estimate_performance(models, name)
Boosted_Results

                           Accuracy
Gradient Boost Classifier      0.84

# Final Betting Model:
- Model has abillity to place a bet on red or blue. Also has abillity to not bet if too risky.
- 0 = bet on Red
- 1 = bet on Blue
- -1 = don't bet

In [12]:
model = Boosted
risk_tolerance = 0.05 #between 0 and 0.5. Will not bet if prediction probabillity is between 1-risk_tolerance and 0+risk_tolerance

In [13]:
predictions = model.predict_proba(test)
predictions = predictions[:,1]
bets = [round(prob) if prob < risk_tolerance or prob>(1-risk_tolerance) else -1 for prob in predictions]

In [14]:
bets_taken = 0
bets_accurate = 0

for i in range(len(bets)):
    if bets[i] != -1:
        bets_taken +=1
        if bets[i] == y_test[i]:
            bets_accurate+=1
            
print("BETS TAKEN:")
print(len(bets),"Potential Bets")
print(bets_taken,"Bets Taken")
print(round(bets_taken/len(bets),2), "Percent Taken")
print("")

print("ACCURACY")
print(bets_accurate, "Accurate Bets")
print(round(bets_accurate/bets_taken,2),"Accuracy on Bets Taken")
print(round(accuracy_score(y_test, model.predict(test)),2),"Baseline Accuracy (on all fights)")

BETS TAKEN:
286 Potential Bets
137 Bets Taken
0.48 Percent Taken

ACCURACY
129 Accurate Bets
0.94 Accuracy on Bets Taken
0.82 Baseline Accuracy (on all fights)